<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
B
response.proto"(
Response
data (	
status (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

