<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 定义数据结构，message 你可以想象成java的class，c语言中的struct
 *
 * Generated from protobuf message <code>Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * 定义一个string类型的字段，字段名字为data, 序号为1
     *
     * Generated from protobuf field <code>string data = 1;</code>
     */
    protected $data = '';
    /**
     * 定义一个int32类型的字段，字段名字为status, 序号为2
     *
     * Generated from protobuf field <code>int32 status = 2;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $data
     *           定义一个string类型的字段，字段名字为data, 序号为1
     *     @type int $status
     *           定义一个int32类型的字段，字段名字为status, 序号为2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * 定义一个string类型的字段，字段名字为data, 序号为1
     *
     * Generated from protobuf field <code>string data = 1;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * 定义一个string类型的字段，字段名字为data, 序号为1
     *
     * Generated from protobuf field <code>string data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     * 定义一个int32类型的字段，字段名字为status, 序号为2
     *
     * Generated from protobuf field <code>int32 status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * 定义一个int32类型的字段，字段名字为status, 序号为2
     *
     * Generated from protobuf field <code>int32 status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

}

